[package]
name = "BB_lopdf"
version = "0.1.0"
edition = "2024"

[dependencies]
lopdf = "0.38"
glob = "0.3"
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
svg2pdf = "0.13"
pdf-writer = "0.12"